[package]
name = "parclone"
version = "0.1.0"
authors = ["Jordi Carrillo <jordilin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boss = { git = "https://github.com/jordilin/boss" }
